### ISSUE TITLE
postprocess handler actually references preprocess

### ISSUE THREAD

**Issue by mkeilman** [radiasoft/rsopt#121]
https://github.com/radiasoft/rsopt/blob/6d4d123dd61e30c7f562b2f5a28c3ccbbcddbde3/rsopt/configuration/setup.py#L118-L119

**Comment by cchall** [comment]
This should be fixed on develop now.
See #97

**Comment by mkeilman** [comment]
OK, I'll close this. Meanwhile, is there something that runs after all the jobs complete, so that one can consolidate output? `postprocess` runs after each job.

**Comment by cchall** [comment]
@mkeilman there isn't currently any option to run something after all jobs complete. My initial thought is that if something like this is a simple, serial call then it lies outside the scope of rsopt and should just be performed by the user or their script after rsopt has completed. The reason being at this point libEnsemble has finished running and rsopt is intended to just be a (large) wrapper around libEnsemble, post-processing is a separate task. If this cleanup is large enough in scope to need many calls or some sort of multiprocessing type work then starting a new libEnsemble run is non-trivial and should probably just be an entirely new configuration file and rsopt execution.
