### ISSUE TITLE
rsopt entrypoint on Windows

### ISSUE THREAD

**Issue by cchall** [radiasoft/rsopt#129]
There are special consideration for running on Windows due to the different handling of multiprocessing compared to linux/mac. Trying to run one of the rsopt examples in the usual manner `rsopt optimize configuration config_chwirut.yaml` results in an error due to the spawned process not having the same value for `libensemble.gen_funcs.rc.aposmm_optimizers` as the parent and trying to import packages that are known to not be installed:

```
available_opt=['nlopt']
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
  File "C:\Users\chris\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\libensemble\gen_funcs\aposmm_localopt_support.py", line 18, in <module>
    from petsc4py import PETSc
ModuleNotFoundError: No module named 'petsc4py'
```

This issue can be fixed by ensuring that the primary run command is inside a `if __name__ == "__main__"` block:
```
from rsopt.pkcli.optimize import configuration

if __name__ == "__main__":
    configuration('config_chwirut.yaml')
```

Looking at the `rsopt` entrypoint generated by pykern on my Mac this is the case:
```
#!/Users/chall/opt/miniconda3/envs/rsopt_p310/bin/python
# -*- coding: utf-8 -*-
import re
import sys
from rsopt.rsopt_console import main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```
On Windows though the entrypoint is a binary executable so apparently something quite different is being done.

**Comment by cchall** [comment]
After some investigation it turns out the reason that the the first example works with spawn is actually `from rsopt.pkcli.optimize import configuration` does have a dependency that import from `local_opt_generate` which detects and sets `libensemble.gen_funcs.rc.aposmm_optimizers` appropriately.

Installing in developer mode on Windows does generate a non-executable version of the console script allowing this to be tested. Setting  `libensemble.gen_funcs.rc.aposmm_optimizers` outside `if __name__ == '__main__'` does allow the script to work without error.

This leaves the question if there is any way to create a general fix for this or if the only option is to require custom run scripts if using Windows.

**Comment by robnagler** [comment]
@cchall If possible, we should avoid supporting Windows directly, and instead ask for people to use Docker.

**Comment by cchall** [comment]
@robnagler the fixes for basic Windows support are already written, but I'll try not to spend too much time going further with this.

**Comment by cchall** [comment]
This is now on master
