### ISSUE TITLE
Add simulation file input from Sirepo schema

### ISSUE THREAD

**Issue by cchall** [radiasoft/rsopt#15]
Current simulation input for non-Python simulations requires users create modules containing their input run files as strings with format fields to be modified by input from generators. While flexible this requires significant setup.

For codes supported by Sirepo rsopt could read in Sirepo-defined configuration files for a simulation. 
This has several advantages:
- Imposes more structure on input files given to rsopt
- Allows manipulation of any parameter in a beamline/command list from the rsopt configuration file without editing the lattice/command file
- The rsbeams StructuredBeamline now has a Sirepo configuration reader for elegant and can be used to dynamically edit the beamline
- The Sirepo schema files allow for validation at optimizer startup

The disadvantages:
- Original input method still needs to be maintained for codes not supported or not fully supported by Sirepo
- Reading and editing existing JSON configuration files and verifying from the schema should be doable with a reasonable amount of new code in rsopt. Writing input files that can be parsed by the actual simulation code, from the JSON, may require copying code from Sirepo. This could be problematic if the code needed is not very self-contained.

Some initial groundwork for this was already done during updates for #14 but problem #*2* needs to addressed before going much further.

**Comment by robnagler** [comment]
There's a lack of encapsulation in sirepo that should be cleaned up. If we could work together to define what you need, we can probably modularize the code so you can import `sirepo.<whatever>` to solve the problem of conversion. This will be useful for more than rsopt: jupyter notebooks need the same thing (see https://github.com/radiasoft/sirepo/pull/2789).

**Comment by cchall** [comment]
This is now implemented for elegant (94093fb3c31b6db07011a74fbb405b8e6342b77a).
Thanks for all the help @robnagler
