### ISSUE TITLE
pyyaml cannot read scientific notation

### ISSUE THREAD

**Issue by cchall** [radiasoft/rsopt#19]
pyyaml will read scientific notation to strings without restrictive formatting requirements: https://github.com/yaml/pyyaml/issues/173. Given that no other scientific software we work with carries such the same restrictions this either needs to be fixed or pyyaml abandoned.

Options so far are:
- drop pykern.pkyaml, directly use pyyaml, and implement  https://stackoverflow.com/questions/30458977/yaml-loads-5e-6-as-string-and-not-a-number 
- switch rsopt to use ruamel.yaml (https://yaml.readthedocs.io/en/latest/index.html). ruamel has been a dependency for rsbeams for a while (also due to lack of features in pyyaml: https://github.com/radiasoft/rsbeams/commit/d6007f5195190b6133a1483d1de8c291bd58f5f0) so this might not be a significant issue

**Comment by robnagler** [comment]
The point of pkyaml is to wrap yaml to fix things with the API. Would you be able to fix pkyaml so that it implements what you need?

**Comment by robnagler** [comment]
@cchall let me know if pkyaml does the right thing. Added pkyaml.dump_pretty, which is not 100% parallel to pkjson.dump_pretty, but the ruamel author thinks dump should not return a string. Anyway, let me know if you want me to build in getting the string back.

**Comment by cchall** [comment]
@robnagler This looks good for now. The YAML load now works as desired. I haven't written the corresponding dump but I don't think there is a case where you want the string back.
