### ISSUE TITLE
organization issues

### ISSUE THREAD

**Issue by cchall** [radiasoft/rsopt#2]
- Should something like TEC utilities be in the codes.warp module? It seems like it should go in rswarp, but it is very problem specific and could quickly clutter up the module if similar things are continually added.

- [x] Log cleanup
- [x] Convert mesh test.py to actual test
- [x] ~~Cleanup Cori installation instruction or move them~~ The particular instructions this was referencing are no long relevant with execution through Shifter. Instructions for rsopt installation (and underlying dependencies) are being added to the documentation though)
- [x] Batch script installation
- [x] Move scripts to pkcli and test
- - [x] run_tec_3d.py
- - [x] run_libE.py
- - [x] Need a method to run through rsmpi (Added in separate issue #7 )

**Comment by robnagler** [comment]
Not sure if this is a question for me, but I'll answer: pkcli modules can be executed by the pkcli wrapper (`rsopt` in this case) pretty much anywhere. The wrapper is a normal python "console" program that then can invoke any module that is installed in the Python environment.

**Comment by cchall** [comment]
Thanks for the explanation @robnagler

**Comment by cchall** [comment]
@robnagler 
Is pkcli supposed to take the place of `scripts` in setuptools? 
I'd also like to include some example batch scripts for showing how to run at NERSC that will be installed by rsopt. However, my test with https://github.com/radiasoft/rsopt/blob/master/rsopt/pkcli/test_libe_submission.sh doesn't show up when I try '$ rsopt'.

**Comment by robnagler** [comment]
You probably want an "install examples" kind of pkcli. Similar to [pykern.pkcli.projex](https://github.com/radiasoft/pykern/blob/6db30f081a2413db641057464f04b06c357f9490/pykern/pkcli/projex.py).

I don't think it is a good idea to install non-Python scripts with setuptools. First of all, these would not be in a place the user could find easily, and second, they aren't Python. Rather, put the scripts in package_data and use pkresource to copy the files to the current directory. This could take some arguments and populate the scripts, too.
