### ISSUE TITLE
running Genesis through Popen

### ISSUE THREAD

**Issue by cchall** [radiasoft/rsopt#39]
Genesis' default behavior when executed is to stop and wait for user input to tell it what file to load. It also has syntax to allow a text file with commands to be passed in automatically. In this case the run command might look like:
```
mpirun -machinefile machinefile_autogen_for_worker_1_task_0 -np 4 --ppn 4 genesis_mpi < genesis_commands.txt
```
Where `genesis_commands.txt` is often just a text file with the name of the actual input file for Genesis. Unfortunately it seems that just trying to use this command with `Popen` and  the default `shell=False` results in Genesis hanging at the user input stage (Genesis does startup and prints a prompt to stdout but never goes further).

**Comment by robnagler** [comment]
Does /dev/stdin as the file work inside mpirun?

**Comment by cchall** [comment]
@robnagler I'm not sure I understand what you are asking. 

I think I have found one solution that works in testing:
```
mpirun -machinefile machinefile_autogen_for_worker_1_task_0 -np 4 --ppn 4 /bin/sh run.sh
```
where run.sh is just 
```
genesis_mpi < genesis_commands.txt
```

**Comment by robnagler** [comment]
A couple of things might be helpful. You might want to use:

```sh
exec genesis_mpi < genesis_commands.txt
```

This will reduce overhead of running processes.

You may also want to:

```sh
mpirun -machinefile machinefile_autogen_for_worker_1_task_0 -np 4 --ppn 4 /bin/bash -c 'exec genesis_mpi < genesis_commands.txt'
```

Again, this will reduce overhead, and probably simplify your code.

**Comment by cchall** [comment]
@robnagler Thanks for suggestions. I'll refactor the command setup. 

It looks like the libEnsemble developers are open to adding access to stdin which should also provide a way to fix this problem, perhaps a little more cleanly.

**Comment by cchall** [comment]
Closing this for now. 266bb43d1802ba335f6838ff71257ca4b41fcaf1 Implements the completed Setup for Genesis.
If libEnsemble is updated with a way to access stdin this can be simplified.
