### ISSUE TITLE
NERSC batch script setup

### ISSUE THREAD

**Issue by cchall** [radiasoft/rsopt#4]
Breaking out the batch script portion of https://github.com/radiasoft/rsopt/issues/2 into a separate issue.

May want to just create a Python launching script that sets environmental variables needed by libEnsemble and then starts the properly configured batch script.

This has the advantage of handing the setup more cleanly and there is no longer a consideration for installing the batch script somewhere on the user's path.

**Comment by robnagler** [comment]
I'm curious if you would be interested in using a curl-based installer so you don't need to install the script on the user's path. I don't know how many users or who they are, but I've found curl-based installers easier to manage.

Another trick we use for Sirepo is to have a public install in a particular user's home directory (mine). Even Open Science Grid did (does?) this.

**Comment by cchall** [comment]
The curl based installer could be worth considering. I'll probably need to move farther along on actually constructing a few use cases and get a more concrete sense what a typical batch script for launching libEnsemble will entail.

My goal here was really to curb the inclination to copy simulation scripts and their execution wrappers out of a version controlled environment, where they then have a tendency to multiply with numerous undocumented changes and create a lot of headaches later. Creating dedicated modules that can be imported or run through a wrapper like pkcli has worked well in rswarp and I was hoping to find a similar solution for the non-Python components here.

**Comment by cchall** [comment]
I don't think this issue is relevant anymore. rsopt handles libEnsemble on NERSC without any special setup needing to be added to the batch script so standard batch script examples are just fine.
