### ISSUE TITLE
NERSC: rpnl not installed

### ISSUE THREAD

**Issue by cchall** [radiasoft/rsopt#40]
Not sure if this is a consequence of the abbreviated installation procedure in place for NERSC or if Sirepo just expects rpnl to be available. 

Looks like the latter. I think it is just installed as part of the SDDS toolkit normally. 
Could be changed to run through Shifter, but you would probably want to make sure all rpn evaluations are performed in one container or the repeated calls to start up Shifter could really slow down the elegant file import.

**Comment by robnagler** [comment]
`rpnl` is installed in the Shifter image. It's not installed by sirepo. The lattice importer uses it to compute elegant variables.

rpnl could be installed manually somehow, perhaps, or maybe it could be run inside shifter.

**Comment by cchall** [comment]
I'm looking at just doing the model parse inside of Shifter. The main issue is that rsopt first parses the model once and then edits a copy before doing write_files every time there is a new job. It looks like the serialized model can be piped out from a subprocess that runs Shifter and parses the files there, and then used used normally by rsopt. If this eventually fails then I suppose the model can be piped into a new subprocess at each job and the write can happen from there.

**Comment by robnagler** [comment]
We would need to write a serializer, which wouldn't be hard. It probably doesn't need to pipe it, but could be a json file, similar to sirepo-data.json files.

**Comment by cchall** [comment]
You can see the approach I tried. It was able to run my test that was failing on NERSC:

https://github.com/radiasoft/rsopt/blob/649be8e56e54422fb387c4e48804460cf4f5ab0c/rsopt/configuration/setup.py#L108-L118

**Comment by robnagler** [comment]
So do you want us to do anything?

**Comment by cchall** [comment]
I don't think so. I'm trying to go through a complete test of the NERSC workflow now. It seems like this piece is working for the time being so I'll probably close this once the changes are merged into develop.

**Comment by cchall** [comment]
Parse to get model is now automatically done in Shifter when `execution_type` is shifter. File write is still handled by Sirepo at the native level even in this case.
Closed by 649be8e56e54422fb387c4e48804460cf4f5ab0c
