### ISSUE TITLE
mpmd dynamically update/install rsopt in Jupyter/rsmpi

### ISSUE THREAD

**Issue by cchall** [radiasoft/rsopt#5]
rsopt is not installed in the containers the rsmpi is running in, and is being updated too rapidly t make installation worthwhile at this point. In the past I would just insert the path to the rsopt directory to allow module imports and this wouldn't be an issue.
However, Warp simulations are now executed via the pkcli wrapper and will not function using this method.

As another workaround I tried calling pip install at the top of the run script:
`subprocess.check_call([sys.executable, "-m", "pip", "install", '/home/vagrant/jupyter/repos/rsopt'])`
and it seemed like it may have worked on some ranks but others failed with:
`ERROR: Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: '/home/vagrant/.pyenv/versions/py3/lib/python3.7/site-packages/rsopt-20200528.164641.dist-info/RECORD.pip'`

@robnagler do you have any suggestions on how I could better handle this?

**Comment by robnagler** [comment]
We could (dynamically) clone rsopt before the simulation runs, and then use `$PYTHONPATH` to point to the install directory. It looks like you are using a fixed path for rspopt so we could define a standard, e.g. `~/jupyter/repos` or `~/jupyter/py3_modules`, and set `$PYTHONPATH` automatically to that directory. We can use `pip install -e` or symbolic links to setup the environment properly. 

We can make it so the environment is compatible with NERSC Shifter. I'm not sure if that's an issue.

Perhaps a call would be useful to talk over the issues.

**Comment by cchall** [comment]
Taking a first pass at setting an install directory 
Tried:
`> pip install --target=/home/vagrant/jupyter/py3_modules .`
`> pip install --target=/home/vagrant/jupyter/py3_modules nlopt`
Using `-e` seemed to break the install process

Then set ` sys.path.insert(1, '/home/vagrant/jupyter/py3_modules')` at the top of the test script. However, I'm missing something because when the libEnsemble executor goes to run rsopt it still can't find it.
> [proxy:0:0@fnl11b.bivio.biz] HYDU_create_process (utils/launch/launch.c:75): execvp error on file rsopt (No such file or directory)

**Comment by robnagler** [comment]
`rsopt` needs to be in `bin`. This can be `~/jupyter/bin`. You need a shim that looks like:

```py
#!/usr/bin/env python
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.path.insert(1, '/home/vagrant/jupyter/py3_modules')
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('pykern', 'console_scripts', 'pykern')()
    )
```

I added the sys.path.insert here.

It seems that when you do `pip install --target`, it installs all dependencies in that directory. I don't think that's a good idea.

**Comment by robnagler** [comment]
@cchall updated the comment

**Comment by robnagler** [comment]
On second thought, I think the script could be simpler. It doesn't need pkg_resources, and would work better:

```py
#!/usr/bin/env python
import os
import rsopt.rsopt_console
import sys

if __name__ == '__main__':
    x = os.environ.get('PYTHONPATH') or ''
    if x:
        x = ':' + x
    os.environ['PYTHONPATH'] = '/home/vagrant/jupyter/py3_modules' + x
    sys.path.insert(1, '/home/vagrant/jupyter/py3_modules')
    sys.exit(rsopt.rsopt_console.main())
```

**Comment by robnagler** [comment]
@cchall and I discussed this, and I'll take over this issue. There are many complications. 

The requirements are:

- rsopt should be easy to install/run
- add bootstrap command to Docker image to make it easy (tab complete)
- dependencies will be installed in the Docker image. They are not updated that frequently.
- some specific dependencies need to be installed:
  - develop branch of https://github.com/Libensemble/libensemble
  - https://pypi.org/project/DFO-LS/
  - https://pypi.org/project/nlopt/

**Comment by robnagler** [comment]
All the dependencies are in beamsim. A clone and install of rsopt is two seconds so we'll just do that in the container before server startup in [radia-run.sh](https://github.com/radiasoft/jupyter.radiasoft.org/blob/master/radia-run.sh). This way we can always take it out if there are performance issues.

For this to happen, we need a new release of beamsim-jupyter. I'll push to alpha now

**Comment by cchall** [comment]
Install process seems to be work well on beta.
See: https://github.com/radiasoft/jupyter.radiasoft.org/issues/102#issuecomment-641351853

**Comment by robnagler** [comment]
Fix https://github.com/radiasoft/jupyter.radiasoft.org/issues/103
