### ISSUE TITLE
Investigate hanging MPI processes when run is stopped

### ISSUE THREAD

**Issue by cchall** [radiasoft/rsopt#54]
Running on our Jupyter server this seems to be a particular issue. Using ctrl+c to stop a run results in a number of hanging subprocesses from MPI and the python subprocess that launched the MPI job. Particularly when rsmpi execution is used the processes seem to hang indefinitely and render the terminal that was running the job completely unusable. 

fenics processor scan script is a good place to start when trying to observe this behavior.

**Comment by robnagler** [comment]
We have had problems running MPI in the past where killing the job (not by control-C but programmatically) leaves the processes running. In the sirepo job supervisor we watch the containers for this state and kill the processes.

I don't really know why this happens, and I figure Docker is the best solution for this. We could stop the container after each mpiexec, but I don't know if that is practical from a performance point of view.

**Comment by cchall** [comment]
Was just reminded this while cleaning up a crashed run. Two rsmpi simulations had failed to stop and just sat for many hours until manually killed.

I'll have to go back and check the log to see if they were started near the time of the crash or froze sometime prior.

**Comment by cchall** [comment]
Looks like both these simulations had frozen well before the crash. Both were on mpi42 and froze ~3 hours before the crash. Probably as a result the manager did not exit for almost 4 hours after the worker crashed. The manager also only produced a dump of persis_info and no history dump. Possibly because it was waiting on the two frozen workers?

**Comment by robnagler** [comment]
I had to hard reboot the node. The NFS daemon was in a weird state. Couldn't even `lsof`.

**Comment by cchall** [comment]
During the upgrade to libEnsemble 0.8.0 I realized that I had not been setting `subgroup_launch` explicitly. According to [libEnsemble documentation](https://libensemble.readthedocs.io/en/latest/executor/mpi_executor.html?highlight=subgroup) this needs to be set properly for tasks to be killed. 
Default is normally to `True`. Setting this to `False` seems like it may have resolved this problem for rsmpi launch https://github.com/radiasoft/rsopt/blob/a6a5aaef1848af14faf5c374f7b207c69b4166a2/rsopt/package_data/executor_schema.yml#L9.
