### ISSUE TITLE
Use of libEnsemble MPIExecutor on rsmpi

### ISSUE THREAD

**Issue by cchall** [radiasoft/rsopt#7]
Launching libEnsemble via rsmpi without an executor all workers can operate on rsmpi servers directly.
However, with an executor, libEnsemble generates hostfiles and attempts to launch using a command like: 

`mpirun -machinefile machinefile_autogen_for_worker_3_task_0 -np 4 --ppn 4 /home/vagrant/.pyenv/versions/py3/bin/python create_field_map.py ./design_1/1eaf29a4-291c-4bc5-96d2-a2a79378d036.yaml 25 3 256 --concatenate --perfect`

In the past it was possible to hack in the rsmpi run command:

> from libensemble.mpi_controller import MPIJobController
> jobctrl = MPIJobController(auto_resources=False)
> 
> rsmpi_command = ['rsmpi', '-h {hostlist}', '-n {num_procs}']
> jobctrl.mpi_command = rsmpi_command
> 
> from libensemble.mpi_resources import MPIResources
> jobctrl.resources = MPIResources(top_level_dir=jobctrl.top_level_dir,
>                                  central_mode=False,
>                                  launcher=jobctrl.mpi_command[0],
>                                  nodelist_env_slurm=None,
>                                  nodelist_env_cobalt=None,
>                                  nodelist_env_lsf=None,
>                                  nodelist_env_lsf_shortform=None)
> print(jobctrl.resources.global_nodelist, jobctrl.resources.physical_cores_avail_per_node)

However, the Exectutor has undergone some revision and this should be re-tested. It would be ideal to use the libEnsemble option provided to set the custom command. See: https://github.com/Libensemble/libensemble/blob/develop/libensemble/executors/mpi_executor.py#L37

**Comment by robnagler** [comment]
It might work to:

```py
jobctrl.mpi_runner = 'custom'
jobctrl.runner_name = 'libensemble-rsmpi'
```

Where `~/jupyter/bin/libensemble-rsmpi` wraps the args.

They probably want you to write a custom MPIRunner, but there's no obvious way to do this without monkeypatching.

**Comment by cchall** [comment]
Added in a781933a2969d8760ae91a0ae9ba35c110f92228
