### ISSUE TITLE
local_opt_generator fails

### ISSUE THREAD

**Issue by mkeilman** [radiasoft/rsopt#80]
The model ```libensemble.tools.gen_support``` referenced in ```local_opt_generator``` does not exist, so rsopt fails when trying to import it. The libensemble repo says the module was removed on 5 October (see [here](https://github.com/Libensemble/libensemble/commit/6f8db3413a4d5fcb3180a3f35b0561d7972ca272#diff-92652e1bb9bf3200610cf268597cd445a40ad5b9e1cc943182093117f12978b8)). Also see [this wiki entry](https://github.com/Libensemble/libensemble/wiki/Updating-for-libEnsemble-v0.8.0) which points to how to do things now.

**Comment by cchall** [comment]
Yes, the update to libensemble 0.8.0 brings a lot of changes. I forgot that we install libensemble from PyPI and have the up-to-date version.

I'll start work making rsopt 0.8 compatible.

**Comment by robnagler** [comment]
We can work with the older version. Did you fix the versions in the setup.py?

**Comment by cchall** [comment]
@robnagler this needed to be updated anyway to get features I want for future work so I went ahead and finally did the work
@mkeilman rsopt develop branch should now be compatible with libensemble 0.8.0. If you get a change to test let me know. I'm going to run a few more tests to verify rsmpi works and then I'll merge it to main soon.

**Comment by cchall** [comment]
Also closed by c01a3da1aacf523057911952db475a271a909cdf
