### ISSUE TITLE
Add option to specify history dump file name

### ISSUE THREAD

**Issue by cchall** [radiasoft/rsopt#84]

**Comment by cchall** [comment]
@mkeilman This should now be implemented on develop. There is a new option option `output_file` that can be used to give the output filenames (*without* extension). So in the configuration file: 
```
...
options:
  output_file: scan_results
  ...
```
will save the final numpy array history to `scan_results.npy` and save the persis_info state to `scan_results.pickle`

**Comment by mkeilman** [comment]
Thanks - I've tested it and it works fine for me
