### ISSUE TITLE
Allow setting the random seed used by libensemble

### ISSUE THREAD

**Issue by mkeilman** [radiasoft/rsopt#88]
See also #87. There is some infrastructure in place for it in  ```options_schema.yml``` and ```options.py```.

**Comment by cchall** [comment]
@mkeilman  the `seed` option in `options.py` is easy to enable so this can be done, but I'm still working on how to best resolve #89 before this can be used.

**Comment by cchall** [comment]
This is now in place on develop. Documentation for the behavior of seed (which follows the settings for libEnsemble's `add_unique_random_streams`) can be seen at: https://rsopt.readthedocs.io/en/develop/samplers/lh_scan.html#options. Does this look like it will work for you @mkeilman ?

**Comment by mkeilman** [comment]
I have tried it and it does work.  Thanks!

**Comment by cchall** [comment]
This is now merged into master
